{"stats": {"errors": 1, "failures": 0, "passes": 1, "skipped": 0, "encoding": "UTF-8", "total": 2}, "results": [{"classname": "index_test:FieldElementTest", "name": "test_mul", "time": 0.0005717277526855469, "type": "success"}, {"classname": "index_test:FieldElementTest", "name": "test_pow", "time": 0.0002148151397705078, "type": "error", "errtype": "builtins.NameError", "message": "name 'other' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/jonastesterelli/ecc-mul-pow-jsong-pb-sf-072618/test/index_test.py\", line 13, in test_pow\n    self.assertEqual(a**3, FieldElement(15, 31))\n  File \"/home/jonastesterelli/ecc-mul-pow-jsong-pb-sf-072618/index.ipynb\", line 70, in __pow__\n    \"464\\n\",\nNameError: name 'other' is not defined\n"}]}